In [2]:
import numpy as np

a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [10]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

#向量化方法
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print('计算结果： '+str(c))
print('向量化方法: '+str(1000*(toc-tic))+'ms')

#循环方法
c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print('计算结果： '+str(c))
print('loop方法: '+str(1000*(toc-tic))+'ms')

计算结果： 250152.78495412727
向量化方法: 0.7562637329101562ms
计算结果： 250152.7849541371
loop方法: 518.8984870910645ms


In [12]:
#numpy定义矩阵/向量
n=np.zeros((10,1))
print(n)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [16]:
d=np.array([-1,-2,3,4])
np.maximum(d,0)

array([ 0.36787944,  0.13533528, 20.08553692, 54.59815003])