In [1]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal=A.sum(axis=0) #竖直相加 while axis=1 means 水平相加
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage=100*A/cal.reshape([1,4]) #broadcast：对应相除
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [14]:
B=np.array([1,2,3,4])
print(B+100) #broadcast:对应相加

C=np.array([[1,2,3],[4,5,6]])
D=np.array([100,100,100])
print(C+D) #broadcast:对应相加
#以上两例子是水平对应相加，竖直也是一样

[101 102 103 104]
[[101 102 103]
 [104 105 106]]


In [15]:
#Normalize 归一化
def normalizeRows(x):
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True) #按行归一化！（axis=1 按行相加）
    x=x/x_norm
    return x
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
