In [1]:
import numpy as np
a=np.random.randn(5) #五个gauss变量
print(a)

[-0.74411379 -0.6659272   2.1523713   0.02828432  0.3169315 ]


In [6]:
print(a.shape) #可以看到，在python中a并不是一个向量，而是一个秩为1的数组（rank 1 array）
print(a.T) #将其转置，也不会得到列向量，还和原来一样
#在编程中，我们应当避免使用这种数据结构！
a.reshape((5,1)) #使用reshape将其转为vector

(5, 1)
[[ 0.67105363 -0.48824631  1.10723792  0.77564172 -1.50909792]]


array([[ 0.67105363],
       [-0.48824631],
       [ 1.10723792],
       [ 0.77564172],
       [-1.50909792]])

In [5]:
a=np.random.randn(5,1) #5行1列，列向量！
print(a.shape)
print(a) #列向量vector
print(a.T) #行向量
assert(a.shape==(5,1)) #断言：若条件不为真，程序会抛出异常

(5, 1)
[[ 0.67105363]
 [-0.48824631]
 [ 1.10723792]
 [ 0.77564172]
 [-1.50909792]]
[[ 0.67105363 -0.48824631  1.10723792  0.77564172 -1.50909792]]


In [7]:
A=np.array([1,2,3,4])
B=np.array([1,2,3,4])
np.outer(A,B)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [8]:
#图像处理时，输入通常是一个三位矩阵（RGB三色，每色对应一个二维矩阵）
def image2vector(image):
    v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    return v
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print(image.shape[0]) #3页（每页是一个二维矩阵）
print(image.shape[1]) #3行
print(image.shape[2]) #2列
print ("image2vector(image) = " + str(image2vector(image)))

3
3
2
image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
